name: Evol-back CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Use .env.test
        run: cp .env.test .env

      - name: Setup de PostgreSQL
        run: docker run -d -name evol-postgres -p 5432 -e POSTGRES_USER=evoladmin -e POSTGRES_PASSWORD=evolpassword -e POSTGRES_DB=evol-db postgres:latest

      - name: Wait for PostgreSQL
        run: |
          echo "Waiting for PostgreSQL..."
          until docker exec evol-postgres pg_isready -U evoladmin -d evol-db; do
            sleep 1
          done

      - name: Run tests
        run: npm test

      - name: Cleanup
        run: docker-compose down
