# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Evol-back CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - run: npm install
      
      # Load .env file and set environment variables
      - name: Load environment variables
        run: |
          if [ -f .env.test ]; then
            export $(cat .env.test | xargs)
          fi

      # Start PostgreSQL service with Docker Compose
      - name: Start PostgreSQL service
        run: docker-compose up -d
      
      # Wait for PostgreSQL to be ready
      - name: Wait for PostgreSQL
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          while ! docker exec ${{ secrets.POSTGRES_CONTAINER_NAME }} pg_isready -U ${{ secrets.POSTGRES_USER }}; do
            sleep 1
          done
      
      # Run tests
      - run: npm test

      # Stop and remove Docker containers
      - name: Stop and remove Docker containers
        run: docker-compose down
